df_cart/urls.py
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import views
urlpatterns = [
    url(r'^$',views.cart),
    url(r'^add(\d+)_(\d+)/$',views.add),
    url(r'^edit(\d+)_(\d+)/$',views.edit),
    url(r'^delete(\d+)/$',views.delete),
]

df_user/urls.py
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import views
urlpatterns = [
    url(r'^register/$',views.register),
    url(r'^register_handle/$',views.register_handle),
    url(r'^login/$',views.login),
    url(r'^login_hander/$',views.login_hander),
    url(r'^info/$',views.info),
    url(r'^order/$',views.order),
    url(r'^center_site/$',views.center_site),
    url(r'^loginout/$',views.loginout),
    url(r'^user_order_(\d)/$',views.user_centent_order),
]

tiantian1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import df_goods.views as gviews
import df_user.views as uviews
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', uviews.login),
    url(r'^user/',include('df_user.urls')),
    url(r'^cart/',include('df_cart.urls')),
    url(r'^order/',include('df_order.urls')),
    url(r'^goods/',include('df_goods.urls')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^list(\d+)_(\d+)_(\d+)/$',gviews.list),
    url(r'^(\d+)/$',gviews.detail),

]

df_order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from df_cart.models import CartInfo
from df_user.models import UserInfo
from df_goods.models import GoodInfo
# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey(UserInfo)
    odata = models.DateField(auto_now=True)
    isPlay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6,decimal_places=2)#总计
    oaddress = models.CharField(max_length=100)

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey(GoodInfo)
    order = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    num = models.IntegerField()

df_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ushou = models.CharField(max_length=10,default='')
    uaddress = models.CharField(max_length=100,default='')
    zipCode = models.CharField(max_length=6,default='')
    phone = models.CharField(max_length=11,default='')

df_user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from models import *
from hashlib import sha1
from django.http import JsonResponse,HttpResponseRedirect
import user_decorator
from df_goods.models import *
from df_order.models import *
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
# Create your views here.

def register(request):
    return render(request,'df_user/register.html')

def register_exist(request):
    username = request.GET.get('username')
    count = UserInfo.objects.filter(uname=username).count()
    return JsonResponse({'count':count})

def register_handle(request):
    # 接收用户输入
    post = request.POST
    user_name = post.get('user_name')
    pwd = post.get('pwd')
    cpwd = post.get('cpwd')
    email = post.get('email')
    # 判断密码
    if pwd != cpwd:
        return redirect('/user/register/')
    # 密码加密
    s1 = sha1()
    s1.update(pwd)
    upwd = s1.hexdigest()
    # 创建对象
    user = UserInfo()
    user.uname = user_name
    user.upwd = upwd
    user.uemail = email
    user.save()
    return redirect('/user/login/')

def login(request):
    uname = request.COOKIES.get('uname','')
    context = {'title':'用户登录','error_name':0,'error_pwd':0,'uname':uname}
    return render(request,'df_user/login.html',context)
    pass

def login_hander(request):
    post = request.POST
    username = post.get('username')
    pwd = post.get('pwd')
    jizhu = post.get('jizhu',0)
    s1 = sha1()
    s1.update(pwd)
    upwd = s1.hexdigest()
    user = UserInfo.objects.filter(uname = username)
    if len(user) != 0:
        if upwd == user[0].upwd:
            url = request.COOKIES.get('url','/')
            red = HttpResponseRedirect('/goods/index/')
            if jizhu != 0:
                red.set_cookie('uname',username)
            else:
                red.set_cookie('uname','',max_age=-1)
            request.session['user_id'] = user[0].id
            request.session['user_name'] = user[0].uname
            return red
            pass
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'username': username, 'upwd': upwd}
            return render(request, 'df_user/login.html', context)

    else:
        context = {'title':'用户登录','error_name':1,'error_pwd':0,'username':username,'upwd':upwd}
        return render(request,'df_user/login.html',context)

def loginout(request):
    request.session.flush()
    return redirect('/user/login/')
    pass

@user_decorator.login
def info(request):
    uname = request.COOKIES.get('uname','')
    if len(uname) != 0:
        user = UserInfo.objects.get(uname = uname)
        goods_ids = request.COOKIES.get('goods_ids','')
        goods_ids1 = goods_ids.split(',')
        goods_list = []
        if goods_ids != '':
            for goods_id in goods_ids1:
                goods_list.append(GoodInfo.objects.get(id=int(goods_id)))
                pass
        phone = user.phone
        uemail = user.uemail
        context = {'title':'登陆成功','uname':uname,'phone':phone,'uemail':uemail,'login':1,'goods_list':goods_list}
        return render(request, 'df_user/user_center_info.html', context)
    else:
        context = {'title':'登陆失败','uname': '', 'phone': '', 'uemail': '', 'login': 0}
        return redirect('/user/login')


@user_decorator.login
def order(request):
    uname = request.session['user_name']
    context = {'title': '用户中心','uname':uname}
    return render(request,'df_user/user_center_order.html',context)
    pass

#订单提交，由购物车跳转过来，后转到用户中心的全部订单页面
@user_decorator.login
def user_centent_order(request,pageid):
    uid = request.session.get('user_id')
    order = OrderInfo.objects.filter(user_id = uid).order_by('-oid')
    context = {
        'pagename':1,
        'title':'全部订单',
        'order':order,
        #'uname': request.session['user_name'],
    }
    return render(request,'df_user/user_center_order.html',context)


@user_decorator.login
def center_site(request):
    user = UserInfo.objects.get(id = request.session['user_id'])
    if request.method=='POST':
        post = request.POST
        user.uname = post.get('name')
        user.uaddress = post.get('address')
        user.zipCode = post.get('youbian')
        user.phone = post.get('phone')
        user.save()
    context = {'title':'用户中心','user':user}

    return render(request,'df_user/user_center_site.html',context)
    pass

templates/df_user/login.html
{% extends 'base_foot.html' %}
{% block head %}
        <script type="text/javascript" src="/static/js/register.js"></script>

<script>
    $(function () {
        name_error = false;
        pwd_error = false;
        if({{ error_name }}==1){$('.user_error').html('用户名错误').show();}
        if({{ error_pwd }}==1){$('.pwd_error').html('密码错误').show();}
    });

</script>
{% endblock head %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/goods/index/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_hander/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" checked="checked" value='1'>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/df_user/register.html
{% extends 'base_foot.html' %}
{% block head %}
        <script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'base_foot.html' %}
{% block head %}
    <script>
        $(function () {
            if ({{ login }} == 1){
                 $('.login_btn').hide();
                $('.login_info').show();
            }
        });

    </script>
{% endblock head %}
{% block body %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{ uname }}</em>
				</div>
				<div class="login_btn fl">
					<a href="/user/login">登录</a>
					<span>|</span>
					<a href="/user/register">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="/cart.html">我的购物车</a>
					<span>|</span>
					<a href="/user/order">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ uname }}</li>
							<li><span>email：</span>{{ uemail }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for g in  goods_list%}
                            <li>
                                <a href="/{{ g.id }}/"><img src="/static/{{ g.gpic }}"></a>
                                <h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{ g.gprice }}</span>
                                    <span class="unit">{{ g.gprice }}/{{ g.gunit }}</span>
                                    <a href="#" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
		</div>
	</div>
{% endblock body %}

templates/df_user/user_center_order.html
{% extends 'base_foot.html' %}
{% block head %}
    <script>
        $(function () {
            $('.login_btn').hide();
            $('.login_info').show();
        });
    </script>
{% endblock head %}
{% block body %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{ uname }}</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="/user/order">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/" class="active">· 全部订单</a></li>
				<li><a href="/user/center_site">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

                {% for o in order %}
                    <ul class="order_list_th w978 clearfix">
                        <li class="col01">2016-8-21 17:36:24</li>
                        <li class="col02">订单号：56872934</li>
                        {% if o.isPlay == 1 %}
                            <li class="col02 stress">已支付</li>
                        {% else %}
                            <li class="col02 stress">未支付</li>
                        {% endif %}
                    </ul>
                    <table class="order_list_table w980">
                        <tbody>
                            <tr>
                                <td width="55%">
                                    {% for item in  o.orderdetailinfo_set.all%}
                                        <ul class="order_goods_list clearfix">
                                            <li class="col01"><img src="/static/{{ item.goods.gpic }}"></li>
                                            <li class="col02">{{ item.goods.gtitle }}<em>{{ item.price }}/{{ item.goods.gunit }}</em></li>
                                            <li class="col03">{{ item.num }}</li>
                                            <li class="col04">11.80元</li>
                                        </ul>


                                    {% endfor %}
                                </td>
                                <td width="15%">33.60元</td>
                                {% if o.isPlay == 1 %}
                                    <td width="15%">已付款</td>
                                    <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                                {% else %}
                                    <td width="15%">未付款</td>
                                    <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>

                {% endfor %}

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock body %}

templates/df_user/user_center_site.html
{% extends 'base_foot.html' %}
{% block head %}
    <script>
        $(function () {
                 $('.login_btn').hide();
                $('.login_info').show();
        });
    </script>
{% endblock head %}
{% block body %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>{{ user.uname }}</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/info/">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="/user/order/">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/center_site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }} （{{ user.uname }} 收） {{ user.phone }}  邮编：{{ user.zipCode }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/center_site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="name">
						</div>
						<div class="form_group form_group2" >
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group" >
							<label>邮编：</label>
							<input type="text" name="youbian">
						</div>
						<div class="form_group" >
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}